version: 2
project_name: ingress2gateway-controller

dockers:
  - image_templates:
      - "eladmotola/ingress2gateway-controller:{{ .Version }}-{{ .Arch }}"
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch:
      - amd64
      - arm64
    build_flag_templates:
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.source=https://github.com/eladm/ingress2gateway-controller"

docker_manifests:
  - name_template: "eladmotola/ingress2gateway-controller:{{ .Version }}"
    image_templates:
      - "eladmotola/ingress2gateway-controller:{{ .Version }}-amd64"
      - "eladmotola/ingress2gateway-controller:{{ .Version }}-arm64"

  - name_template: "eladmotola/ingress2gateway-controller:latest"
    image_templates:
      - "eladmotola/ingress2gateway-controller:{{ .Version }}-amd64"
      - "eladmotola/ingress2gateway-controller:{{ .Version }}-arm64"